/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import clases.*;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javafx.application.Platform;
import javafx.embed.swing.JFXPanel;
import javafx.scene.Scene;
import javafx.scene.web.WebView;
import javax.swing.JOptionPane;
/**
 *
 * @author spino
 */
public class Administrador extends javax.swing.JFrame {
    public ArrayList<Viaje> viajes = new ArrayList<>();
    public ArrayList<Chofer> choferes = new ArrayList<>();
    public ArrayList<Camion> camiones = new ArrayList<>();
    JFXPanel jfxPanel;
    Conector conn;
    /**
     * Creates new form Administrador
     */
    public Administrador() {
        initComponents();
        //conn = new Conector();
        //cargarBase();
        
    }
    
    private void cargarBase(){
        ArrayList<String> solicitantes = new ArrayList<>(conn.consultaSQL("SELECT * FROM `TractoGestor`.`Viajes`; ", "solicitante"));
        ArrayList<String> ids = new ArrayList<>(conn.consultaSQL("SELECT * FROM `TractoGestor`.`Viajes`; ", "ID"));
        ArrayList<String> destinos = new ArrayList<>(conn.consultaSQL("SELECT * FROM `TractoGestor`.`Viajes`; ", "destino"));
        ArrayList<String> chofers = new ArrayList<>(conn.consultaSQL("SELECT * FROM `TractoGestor`.`Viajes`; ", "chofer"));
        ArrayList<String> unidades = new ArrayList<>(conn.consultaSQL("SELECT * FROM `TractoGestor`.`Viajes`; ", "unidad"));
        ArrayList<String> fechas = new ArrayList<>(conn.consultaSQL("SELECT * FROM `TractoGestor`.`Viajes`; ", "fecha"));
        for(int i=0;i<solicitantes.size();i++){
            System.out.println(solicitantes.get(i));
            Viaje ini = new Viaje(ids.get(i),fechas.get(i),destinos.get(i),solicitantes.get(i),chofers.get(i),unidades.get(i));
            viajes.add(ini);
        }
        ArrayList<String> nombreC = new ArrayList<>(conn.consultaSQL("SELECT * FROM `TractoGestor`.`choferes`; ", "nombre"));
        ArrayList<String> emails = new ArrayList<>(conn.consultaSQL("SELECT * FROM `TractoGestor`.`choferes`; ", "telefono"));
        ArrayList<String> tels = new ArrayList<>(conn.consultaSQL("SELECT * FROM `TractoGestor`.`choferes`; ", "email"));
        ArrayList<String> lics = new ArrayList<>(conn.consultaSQL("SELECT * FROM `TractoGestor`.`choferes`; ", "licencia"));
        for(int i=0;i<nombreC.size();i++){
            Chofer iniC = new Chofer(nombreC.get(i),emails.get(i),tels.get(i),lics.get(i));
            choferes.add(iniC);
        }
        ArrayList<String> nombreCam = new ArrayList<>(conn.consultaSQL("SELECT * FROM `TractoGestor`.`camiones`; ", "nombre"));
        ArrayList<String> placas = new ArrayList<>(conn.consultaSQL("SELECT * FROM `TractoGestor`.`camiones`; ", "placas"));
        ArrayList<String> modelo = new ArrayList<>(conn.consultaSQL("SELECT * FROM `TractoGestor`.`camiones`; ", "modelo"));
        ArrayList<String> marca = new ArrayList<>(conn.consultaSQL("SELECT * FROM `TractoGestor`.`camiones`; ", "marca"));
        ArrayList<String> ejes = new ArrayList<>(conn.consultaSQL("SELECT * FROM `TractoGestor`.`camiones`; ", "ejes"));
        for(int i=0;i<nombreCam.size();i++){
            Camion inicam = new Camion(nombreCam.get(i),placas.get(i),modelo.get(i),marca.get(i),ejes.get(i));
            camiones.add(inicam);
        }
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        Fondo = new org.edisoncor.gui.panel.Panel();
        Titulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        newViajeB = new javax.swing.JButton();
        RChoferB = new javax.swing.JButton();
        RCamionB = new javax.swing.JButton();
        verViajeB = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        blanco = new javax.swing.JPanel();
        new_viaje = new javax.swing.JPanel();
        new_viaje.setVisible(false);
        jLabel2 = new javax.swing.JLabel();
        solic = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        destino = new javax.swing.JTextField();
        return1 = new javax.swing.JButton();
        CrearV = new javax.swing.JButton();
        jDate = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        choferBox = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        camionBox = new javax.swing.JComboBox<>();
        ver_viaje = new javax.swing.JPanel();
        ver_viaje.setVisible(false);
        viajesIdBox = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        return2 = new javax.swing.JButton();
        Viz_viaje = new javax.swing.JButton();
        registro_chofer = new javax.swing.JPanel();
        registro_chofer.setVisible(false);
        jLabel8 = new javax.swing.JLabel();
        nom_chofer = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        email_chofer = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tel_chofer = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        lic_chofer = new javax.swing.JTextField();
        reg_chofer = new javax.swing.JButton();
        return3 = new javax.swing.JButton();
        registro_cam = new javax.swing.JPanel();
        registro_cam.setVisible(false);
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        nom_cam = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        modelo_cam = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        ejes_cam = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        marca_cam = new javax.swing.JTextField();
        reg_camion = new javax.swing.JButton();
        return4 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        placas_cam = new javax.swing.JTextField();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);
        setPreferredSize(new java.awt.Dimension(1000, 400));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MenuAdmin.jpg"))); // NOI18N
        Fondo.setInheritsPopupMenu(true);
        Fondo.setPreferredSize(new java.awt.Dimension(1400, 500));

        Titulo.setFont(new java.awt.Font("Century", 0, 24)); // NOI18N
        Titulo.setText("Bienvenido: admin");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/user_icon.png"))); // NOI18N

        newViajeB.setBackground(new java.awt.Color(255, 255, 255));
        newViajeB.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        newViajeB.setText("Nuevo Viaje");
        newViajeB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        newViajeB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newViajeBActionPerformed(evt);
            }
        });

        RChoferB.setBackground(new java.awt.Color(255, 255, 255));
        RChoferB.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        RChoferB.setText("Registrar Chofer");
        RChoferB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        RChoferB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RChoferBActionPerformed(evt);
            }
        });

        RCamionB.setBackground(new java.awt.Color(255, 255, 255));
        RCamionB.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        RCamionB.setText("Registrar Camión");
        RCamionB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        RCamionB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RCamionBActionPerformed(evt);
            }
        });

        verViajeB.setBackground(new java.awt.Color(255, 255, 255));
        verViajeB.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        verViajeB.setText("Ver Viaje");
        verViajeB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        verViajeB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verViajeBActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayout(new java.awt.CardLayout());

        blanco.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout blancoLayout = new javax.swing.GroupLayout(blanco);
        blanco.setLayout(blancoLayout);
        blancoLayout.setHorizontalGroup(
            blancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 589, Short.MAX_VALUE)
        );
        blancoLayout.setVerticalGroup(
            blancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );

        jLayeredPane1.add(blanco, "card4");

        new_viaje.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Crear Viaje");

        jLabel3.setText("Solicitante");

        jLabel4.setText("Destino");

        return1.setText("Regresar");
        return1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                return1ActionPerformed(evt);
            }
        });

        CrearV.setText("Crear");
        CrearV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearVActionPerformed(evt);
            }
        });

        jLabel5.setText("Fecha");

        choferBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No hay choferes registrados" }));

        jLabel13.setText("Chofer");

        jLabel14.setText("Camion");

        camionBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No hay unidades registradas" }));

        javax.swing.GroupLayout new_viajeLayout = new javax.swing.GroupLayout(new_viaje);
        new_viaje.setLayout(new_viajeLayout);
        new_viajeLayout.setHorizontalGroup(
            new_viajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(new_viajeLayout.createSequentialGroup()
                .addGap(264, 264, 264)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, new_viajeLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(new_viajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, new_viajeLayout.createSequentialGroup()
                        .addGroup(new_viajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CrearV)
                            .addGroup(new_viajeLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(51, 51, 51)
                                .addComponent(choferBox, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)))
                        .addGroup(new_viajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(new_viajeLayout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(return1)
                                .addGap(140, 140, 140))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, new_viajeLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel14)
                                .addGap(41, 41, 41)
                                .addComponent(camionBox, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, new_viajeLayout.createSequentialGroup()
                        .addGroup(new_viajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(61, 61, 61)
                        .addGroup(new_viajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(destino, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(solic, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDate, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(181, 181, 181))))
        );
        new_viajeLayout.setVerticalGroup(
            new_viajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(new_viajeLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addGap(49, 49, 49)
                .addGroup(new_viajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(solic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGroup(new_viajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(new_viajeLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, new_viajeLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(destino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(new_viajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDate, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGroup(new_viajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(new_viajeLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(CrearV)
                        .addContainerGap(49, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, new_viajeLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(new_viajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(choferBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(camionBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13))
                        .addGap(56, 56, 56)
                        .addComponent(return1)
                        .addGap(21, 21, 21))))
        );

        jLayeredPane1.add(new_viaje, "card2");

        ver_viaje.setBackground(new java.awt.Color(255, 255, 255));

        viajesIdBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ningun viaje registrado" }));
        viajesIdBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viajesIdBoxActionPerformed(evt);
            }
        });

        jLabel7.setText("Selecciona ID del viaje");

        return2.setText("Regresar");
        return2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                return2ActionPerformed(evt);
            }
        });

        Viz_viaje.setText("Visualizar");
        Viz_viaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Viz_viajeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ver_viajeLayout = new javax.swing.GroupLayout(ver_viaje);
        ver_viaje.setLayout(ver_viajeLayout);
        ver_viajeLayout.setHorizontalGroup(
            ver_viajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ver_viajeLayout.createSequentialGroup()
                .addContainerGap(139, Short.MAX_VALUE)
                .addGroup(ver_viajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ver_viajeLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(76, 76, 76)
                        .addComponent(viajesIdBox, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(179, 179, 179))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ver_viajeLayout.createSequentialGroup()
                        .addComponent(return2)
                        .addGap(155, 155, 155))))
            .addGroup(ver_viajeLayout.createSequentialGroup()
                .addGap(264, 264, 264)
                .addComponent(Viz_viaje)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        ver_viajeLayout.setVerticalGroup(
            ver_viajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ver_viajeLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(ver_viajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viajesIdBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(75, 75, 75)
                .addComponent(Viz_viaje)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(return2)
                .addGap(70, 70, 70))
        );

        jLayeredPane1.add(ver_viaje, "card3");

        registro_chofer.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setText("Registrar Chofer");

        jLabel9.setText("Nombre");

        jLabel10.setText("Correo Electrónico");

        jLabel11.setText("Teléfono");

        jLabel12.setText("Licencia");

        reg_chofer.setText("Registrar");
        reg_chofer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reg_choferActionPerformed(evt);
            }
        });

        return3.setText("Regresar");
        return3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                return3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout registro_choferLayout = new javax.swing.GroupLayout(registro_chofer);
        registro_chofer.setLayout(registro_choferLayout);
        registro_choferLayout.setHorizontalGroup(
            registro_choferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registro_choferLayout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(reg_chofer)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registro_choferLayout.createSequentialGroup()
                .addContainerGap(134, Short.MAX_VALUE)
                .addGroup(registro_choferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registro_choferLayout.createSequentialGroup()
                        .addGroup(registro_choferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addGroup(registro_choferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(registro_choferLayout.createSequentialGroup()
                                    .addGroup(registro_choferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel11))
                                    .addGap(16, 16, 16)
                                    .addGroup(registro_choferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tel_chofer, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(email_chofer, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lic_chofer, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(registro_choferLayout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addGap(67, 67, 67)
                                    .addGroup(registro_choferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8)
                                        .addComponent(nom_chofer)))))
                        .addGap(254, 254, 254))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registro_choferLayout.createSequentialGroup()
                        .addComponent(return3)
                        .addGap(104, 104, 104))))
        );
        registro_choferLayout.setVerticalGroup(
            registro_choferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registro_choferLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel8)
                .addGap(52, 52, 52)
                .addGroup(registro_choferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(nom_chofer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(registro_choferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email_chofer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(registro_choferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tel_chofer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(registro_choferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(lic_chofer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(reg_chofer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(return3)
                .addGap(27, 27, 27))
        );

        jLayeredPane1.add(registro_chofer, "card5");

        registro_cam.setBackground(new java.awt.Color(255, 255, 255));

        jLabel15.setText("Registrar Camión");

        jLabel16.setText("Nombre");

        nom_cam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nom_camActionPerformed(evt);
            }
        });

        jLabel17.setText("Modelo");

        modelo_cam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelo_camActionPerformed(evt);
            }
        });

        jLabel18.setText("Ejes");

        ejes_cam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejes_camActionPerformed(evt);
            }
        });

        jLabel19.setText("Marca");

        marca_cam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marca_camActionPerformed(evt);
            }
        });

        reg_camion.setText("Registrar");
        reg_camion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reg_camionActionPerformed(evt);
            }
        });

        return4.setText("Regresar");
        return4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                return4ActionPerformed(evt);
            }
        });

        jLabel20.setText("Placas");

        placas_cam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placas_camActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout registro_camLayout = new javax.swing.GroupLayout(registro_cam);
        registro_cam.setLayout(registro_camLayout);
        registro_camLayout.setHorizontalGroup(
            registro_camLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registro_camLayout.createSequentialGroup()
                .addGroup(registro_camLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(registro_camLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(registro_camLayout.createSequentialGroup()
                            .addGap(317, 317, 317)
                            .addComponent(placas_cam, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(registro_camLayout.createSequentialGroup()
                            .addGap(247, 247, 247)
                            .addComponent(jLabel15)))
                    .addGroup(registro_camLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel20)
                        .addGroup(registro_camLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(registro_camLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nom_cam, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(registro_camLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(modelo_cam, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registro_camLayout.createSequentialGroup()
                                .addGroup(registro_camLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registro_camLayout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addGap(47, 47, 47))
                                    .addGroup(registro_camLayout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addGap(56, 56, 56)))
                                .addGroup(registro_camLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ejes_cam, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(marca_cam, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(registro_camLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(reg_camion)))))
                .addContainerGap(158, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registro_camLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(return4)
                .addGap(124, 124, 124))
        );
        registro_camLayout.setVerticalGroup(
            registro_camLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registro_camLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel15)
                .addGap(38, 38, 38)
                .addGroup(registro_camLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(placas_cam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registro_camLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nom_cam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(5, 5, 5)
                .addGroup(registro_camLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modelo_cam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registro_camLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(marca_cam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registro_camLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ejes_cam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(reg_camion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(return4)
                .addGap(66, 66, 66))
        );

        jLayeredPane1.add(registro_cam, "card6");

        javax.swing.GroupLayout FondoLayout = new javax.swing.GroupLayout(Fondo);
        Fondo.setLayout(FondoLayout);
        FondoLayout.setHorizontalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FondoLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel1)
                        .addGap(296, 296, 296)
                        .addComponent(Titulo))
                    .addGroup(FondoLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newViajeB, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RChoferB, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RCamionB, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(verViajeB, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(123, 123, 123)
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(494, Short.MAX_VALUE))
        );
        FondoLayout.setVerticalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(FondoLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(Titulo)))
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FondoLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(newViajeB, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(RChoferB, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(RCamionB, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(verViajeB, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FondoLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 136, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RChoferBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RChoferBActionPerformed
        // TODO add your handling code here:
        registro_chofer.setVisible(true);
        blanco.setVisible(false);
        newViajeB.setVisible(false);
        RChoferB.setVisible(true);
        RCamionB.setVisible(false);
        verViajeB.setVisible(false);
        
    }//GEN-LAST:event_RChoferBActionPerformed

    private void newViajeBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newViajeBActionPerformed
        // TODO add your handling code here:
        new_viaje.setVisible(true);
        blanco.setVisible(false);
        RChoferB.setVisible(false);
        RChoferB.setVisible(false);
        RCamionB.setVisible(false);
        verViajeB.setVisible(false);
        
        if(choferes.isEmpty()){
            
        }else{
            choferBox.setModel(new javax.swing.DefaultComboBoxModel<>(getNomsChoferes()));
        }
        if(camiones.isEmpty()){
            
        }else{
            camionBox.setModel(new javax.swing.DefaultComboBoxModel<>(getInfoCamion()));
        }
    }//GEN-LAST:event_newViajeBActionPerformed

    private void return1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_return1ActionPerformed
        // TODO add your handling code here:
        new_viaje.setVisible(false);
        blanco.setVisible(true);
        RChoferB.setVisible(true);
        //newViajeB.setVisible(true);
        RChoferB.setVisible(true);
        RCamionB.setVisible(true);
        verViajeB.setVisible(true);
        
        destino.setText(null);
        solic.setText(null);
    }//GEN-LAST:event_return1ActionPerformed

    private void CrearVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearVActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat df= new SimpleDateFormat("dd-MM-yyyy");
        String date = "";
        try{
        date = df.format(jDate.getDate());
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Ingresa una fecha valida","Error",JOptionPane.ERROR_MESSAGE);
        }
        String ids;
        if(!viajes.isEmpty()){
            ids = viajes.get(viajes.size()-1).getId()+1;
        }else
            ids = "1";
        String destinox = destino.getText();
        String sol = solic.getText();
        String chofer = (String)choferBox.getSelectedItem();
        String camion = (String)camionBox.getSelectedItem();
        if(destinox.equals("") || sol.equals("") || ids == null ){
            JOptionPane.showMessageDialog(null,"Datos Incompletos","Error",JOptionPane.ERROR_MESSAGE);
        }else{
            Viaje vi = new Viaje(ids,date,destinox,sol,chofer,camion);
            viajes.add(vi);
            JOptionPane.showMessageDialog(null,"Datos del Viaje: \n"
                    + "ID: "+ids+"\n"
                    + "Fecha: "+date+"\n"
                    + "Destino: "+destinox+"\n"
                    + "Solicitante: "+sol+"\n"
                    + "Chofer: "+chofer+"\n"
                    + "Unidad: "+camion,"Viaje Creado",1);
            conn.altaSQL("INSERT INTO `TractoGestor`.`Viajes` "+"VALUES ('"+date+"','"+destinox+"','"+sol+"','"+chofer+"','"+camion+"')");
        }
        
        destino.setText(null);
        solic.setText(null);
        
        
    }//GEN-LAST:event_CrearVActionPerformed

    private void verViajeBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verViajeBActionPerformed
        // TODO add your handling code here:
        blanco.setVisible(false);
        ver_viaje.setVisible(true);
        RChoferB.setVisible(false);
        RCamionB.setVisible(false);
        verViajeB.setVisible(true);
        
        newViajeB.setVisible(false);
        if(viajes.isEmpty()){
            
        }else{
            viajesIdBox.setModel(new javax.swing.DefaultComboBoxModel<>(getIdArray()));
        }
        if(jfxPanel.isVisible())
            jfxPanel.setVisible(false);
    }//GEN-LAST:event_verViajeBActionPerformed

    private void return2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_return2ActionPerformed
        // TODO add your handling code here:
        ver_viaje.setVisible(false);
        blanco.setVisible(true);
        RChoferB.setVisible(true);
        newViajeB.setVisible(true);
        RChoferB.setVisible(true);
        RCamionB.setVisible(true);
        //verViajeB.setVisible(true);
        
    }//GEN-LAST:event_return2ActionPerformed

    private void viajesIdBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viajesIdBoxActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_viajesIdBoxActionPerformed

    private void reg_choferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reg_choferActionPerformed
        // TODO add your handling code here:
        String nom = nom_chofer.getText();
        String tel = tel_chofer.getText();
        String email = email_chofer.getText();
        //
        Pattern pattern = Pattern.compile("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@" + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$");
 
        
       // String emailmuestra = "email@email.com";
 
        Matcher mather = pattern.matcher(email);
 
        if (mather.find() == true) {
            System.out.println("El email ingresado es válido.");
        } else {
            System.out.println("El email ingresado es inválido.");
            email = null;
        }
        //
        String lic = lic_chofer.getText();
        if(nom.equals("") || tel.equals("") || email == null || lic == null ){
            JOptionPane.showMessageDialog(null,"Datos Erroneos","Error",JOptionPane.ERROR_MESSAGE);
        }else{
            
            Chofer c = new Chofer(nom,tel,email,lic);
            choferes.add(c);
            JOptionPane.showMessageDialog(null,"Datos del Chofer: \n"
                    + "Nombre: "+nom+"\n"
                    + "Telefono: "+tel+"\n"
                    + "Correo: "+email+"\n"
                    + "Licencia: "+lic,"Chofer Registrado",1);
            conn.altaSQL("INSERT INTO `TractoGestor`.`choferes` "+"VALUES ('"+nom+"','"+tel+"','"+email+"','"+lic+"')");
        }
        nom_chofer.setText(null);
        email_chofer.setText(null);
        tel_chofer.setText(null);
        lic_chofer.setText(null);
    }//GEN-LAST:event_reg_choferActionPerformed

    private void return3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_return3ActionPerformed
        // TODO add your handling code here:
        registro_chofer.setVisible(false);
        blanco.setVisible(true);
        RChoferB.setVisible(true);
        newViajeB.setVisible(true);
        verViajeB.setVisible(true);
        RCamionB.setVisible(true);
        //verViajeB.setVisible(true);
        
        nom_chofer.setText(null);
        email_chofer.setText(null);
        tel_chofer.setText(null);
        lic_chofer.setText(null);
    }//GEN-LAST:event_return3ActionPerformed

    private void nom_camActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nom_camActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nom_camActionPerformed

    private void modelo_camActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelo_camActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelo_camActionPerformed

    private void ejes_camActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejes_camActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ejes_camActionPerformed

    private void marca_camActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marca_camActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marca_camActionPerformed

    private void reg_camionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reg_camionActionPerformed
        // TODO add your handling code here:
        String placas = placas_cam.getText();
        String modelo = modelo_cam.getText();
        String marca = marca_cam.getText();
        String ejes = ejes_cam.getText();
        String nombre = nom_cam.getText();
        if(nombre.equals("") || placas.equals("") || modelo.equals("") || marca == null || ejes == null ){
            JOptionPane.showMessageDialog(null,"Datos Incompletos","Error",JOptionPane.ERROR_MESSAGE);
        }else{
            
            Camion c = new Camion(nombre,placas,modelo,marca,ejes);
            camiones.add(c);
            JOptionPane.showMessageDialog(null,"Datos del Camión: \n"
                    + "Nombre: "+nombre+"\n"
                    + "Placas: "+placas+"\n"
                    + "Modelo: "+modelo+"\n"
                    + "Marca: "+marca+"\n"
                    + "Ejes: "+ejes,"Camion Registrado",1);
            conn.altaSQL("INSERT INTO `TractoGestor`.`camiones` "+"VALUES ('"+nombre+"','"+placas+"','"+modelo+"','"+marca+"','"+ejes+"')");
        }
        placas_cam.setText(null);
        modelo_cam.setText(null);
        marca_cam.setText(null);
        nom_cam.setText(null);
        ejes_cam.setText(null);
    }//GEN-LAST:event_reg_camionActionPerformed

    private void return4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_return4ActionPerformed
        // TODO add your handling code here:
        registro_cam.setVisible(false);
        blanco.setVisible(true);
        RChoferB.setVisible(true);
        newViajeB.setVisible(true);
        verViajeB.setVisible(true);
        //RCamionB.setVisible(true);
        
        placas_cam.setText(null);
        modelo_cam.setText(null);
        ejes_cam.setText(null);
        marca_cam.setText(null);
        nom_cam.setText(null);
    }//GEN-LAST:event_return4ActionPerformed

    private void placas_camActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placas_camActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_placas_camActionPerformed

    private void RCamionBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RCamionBActionPerformed
        // TODO add your handling code here:
        blanco.setVisible(false);
        registro_cam.setVisible(true);
        RChoferB.setVisible(false);
        //RCamionB.setVisible(true);
        verViajeB.setVisible(false);
        
        newViajeB.setVisible(false);
        
    }//GEN-LAST:event_RCamionBActionPerformed

    private void Viz_viajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Viz_viajeActionPerformed
        // TODO add your handling code here:
        String idviaje = (String)viajesIdBox.getSelectedItem();
        if( !idviaje.equals("Ningun viaje registrado")){
            for(int i=0;i<viajes.size();i++){
                if(viajes.get(i).getId().equals(idviaje)){
                    JOptionPane.showMessageDialog(null,"Datos del Viaje: \n"
                        + "Fecha: "+viajes.get(i).getFecha()+"\n"
                        + "Destino: "+viajes.get(i).getDestino()+"\n"
                        + "Solicitante: "+viajes.get(i).getSoli()+"\n"
                        + "Chofer: "+viajes.get(i).getChofer()+"\n"
                        + "Unidad: "+viajes.get(i).getCamion(),"Viaje Creado",1);
                    
                    
                    //PAGINA GENERADA
                    
                    jfxPanel = new JFXPanel();
                   
        jLayeredPane1.add(jfxPanel, "card6");
        jfxPanel.setVisible(true);
        ver_viaje.setVisible(false);

        String html = "<!DOCTYPE html>\n" +
"<html>\n" +
"  <head>\n" +
"    <style>\n" +
"      #map {\n" +
"        height: 500px; \n" +
"        width: 100%;\n" +
"       }\n" +
"    </style>\n" +
"     <script src=\"https://unpkg.com/axios/dist/axios.min.js\"></script>\n" +
"  </head>\n" +
"  <body>\n" +
"    <h3>TractoGestor</h3>\n" +
"    <div id=\"map\"></div>\n" +
"    <script>\n" +
"function initMap() {\n" +
"  var directionsService = new google.maps.DirectionsService;\n" +
"  var directionsDisplay = new google.maps.DirectionsRenderer;\n" +
"  var options = {\n" +
"    zoom:11,\n" +
"    center: {lat: 19.432608, lng: -99.133209} //center at MexicoCity\n" +
"  };\n" +
"  var map = new google.maps.Map(\n" +
"      document.getElementById('map'), options);\n" +
"    var locations = [];\n" +
"     function addMarker(location, distancia, tiempo){\n" +
"      var marker = new google.maps.Marker({\n" +
"        position: location,\n" +
"        map:map,\n" +
"        icon: 'http://maps.google.com/mapfiles/ms/micons/truck.png',\n" +
"        content: '<h1> "+viajes.get(i).getCamion()+"</br>Distancia: '+distancia+\n" +
"                '</br>Tiempo aprox. '+tiempo+\n" +
"                '</br>Costo '+parseFloat(distancia) * 1.3 +'MXN</h1>'\n" +                
"      });\n" +
"        var infoWindow = new google.maps.InfoWindow({\n" +
"          content: marker.content\n" +
"        });\n" +
"        marker.addListener('click', function(){\n" +
"          infoWindow.open(map,marker);\n" +
"        });\n" +
"    }\n" +
"    geocode();\n" +
"    function geocode(e){\n" +
"      var location = \"Ciudad de Mexico\";\n" +
"      axios.get('https://maps.googleapis.com/maps/api/geocode/json',{\n" +
"        params:{\n" +
"          address:location,\n" +
"          key:'AIzaSyBM1McG3Nt11aw1UW2_0R0JpFIpCUKvaAw'\n" +
"        }\n" +
"      })\n" +
"      .then(function(response){\n" +
"        locations.push(response.data.results[0].geometry.location);\n" +
"        var locationxx = response.data.results[0].geometry.location;\n" +
"        var service = new google.maps.DistanceMatrixService();\n" +
"service.getDistanceMatrix(\n" +
"  {\n" +
"    origins: [location],\n" +
"    destinations: [location2],\n" +
"    travelMode: 'DRIVING'\n" +
"  }, callback);\n" +
"  function callback(response, status) {\n" +
"  if (status === 'OK') {\n" +
"    var origins = response.originAddresses;\n" +
"    for (var i = 0; i < origins.length; i++) {\n" +
"      var results = response.rows[i].elements;\n" +
"      for (var j = 0; j < results.length; j++) {\n" +
"        var element = results[j];\n" +
"        var distance = element.distance.text;\n" +
"        var duration = element.duration.text;\n" +
"        addMarker(locationxx,distance, duration);\n" +
"      }\n" +
"    }\n" +
"  }\n" +
"}\n" +
"      })\n" +
"      .catch(function(error){\n" +
"        console.log(error);\n" +
"      });\n" +
"       var location2 = \""+viajes.get(i).getDestino()+"\";\n" +
"       axios.get('https://maps.googleapis.com/maps/api/geocode/json',{\n" +
"        params:{\n" +
"          address:location2,\n" +
"          key:'AIzaSyBM1McG3Nt11aw1UW2_0R0JpFIpCUKvaAw'\n" +
"        }\n" +
"      })\n" +
"      .then(function(response){\n" +
"        locations.push(response.data.results[0].geometry.location);\n" +
"      })\n" +
"      .catch(function(error){\n" +
"        console.log(error);\n" +
"      });\n" +
"        directionsDisplay.setMap(map);\n" +
"         calculateAndDisplayRoute(directionsService, directionsDisplay, location,location2);\n" +
"    } \n" +
"}\n" +
"      \n" +
"function calculateAndDisplayRoute(directionsService, directionsDisplay, origen, destination) {\n" +
"        directionsService.route({\n" +
"          origin: origen,\n" +
"          destination: destination,\n" +
"          travelMode: 'DRIVING'\n" +
"          //departure_time: \"now\"\n" +
"        }, function(response, status) {\n" +
"          if (status === 'OK') {\n" +
"            directionsDisplay.setDirections(response);\n" +
"          } else {\n" +
"            alert('Directions request failed due to ' + status);\n" +
"          }\n" +
"        });\n" +
"      }\n" +
"    </script>\n" +
"    <script async defer\n" +
"    src=\"https://maps.googleapis.com/maps/api/js?key=AIzaSyBM1McG3Nt11aw1UW2_0R0JpFIpCUKvaAw&callback=initMap\">\n" +
"    \n" +
"    </script>\n" +
"  </body>\n" +
"</html>";
        File f = new File("src/paginas/htmlprueba.html");
        try {
            try (BufferedWriter bw = new BufferedWriter(new FileWriter(f))) {
                bw.write(html);
                bw.close();
            }
        } catch (IOException ex) {
            Logger.getLogger(Administrador.class.getName()).log(Level.SEVERE, null, ex);
        }
// Creation of scene and future interactions with JFXPanel
// should take place on the JavaFX Application Thread
Platform.runLater(() -> {
    WebView webView = new WebView();
    jfxPanel.setScene(new Scene(webView));
    webView.getEngine().load("file:///C:/Users/Usuario/Documents/NetBeansProjects/Proyecto%20ADOO/src/paginas/htmlprueba.html");
});

                }
            }
        }else
            JOptionPane.showMessageDialog(null,"No hay viajes registrados","Error",JOptionPane.ERROR_MESSAGE);
        
        
        
    }//GEN-LAST:event_Viz_viajeActionPerformed

    public String[] getIdArray(){
        String[] ids = new String[viajes.size()];
        for(int i=0;i<viajes.size();i++){
            String cadena = viajes.get(i).getId();
            ids[i] = cadena;
        }
        return ids;
    }
    
    public String[] getNomsChoferes(){
        String[] noms = new String[choferes.size()];
        for(int i=0;i<choferes.size();i++){
            noms[i] = choferes.get(i).getNom();
        }
        return noms;
    }
    
    public String[] getInfoCamion(){
        String[] info = new String[camiones.size()];
        for(int i=0;i<camiones.size();i++){
            info[i] = camiones.get(i).getNom()+" "+camiones.get(i).getModelo();
        }
        return info;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Administrador().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CrearV;
    private org.edisoncor.gui.panel.Panel Fondo;
    private javax.swing.JButton RCamionB;
    private javax.swing.JButton RChoferB;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton Viz_viaje;
    private javax.swing.JPanel blanco;
    private javax.swing.JComboBox<String> camionBox;
    private javax.swing.JComboBox<String> choferBox;
    private javax.swing.JTextField destino;
    private javax.swing.JTextField ejes_cam;
    private javax.swing.JTextField email_chofer;
    private com.toedter.calendar.JDateChooser jDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JTextField lic_chofer;
    private javax.swing.JTextField marca_cam;
    private javax.swing.JTextField modelo_cam;
    private javax.swing.JButton newViajeB;
    private javax.swing.JPanel new_viaje;
    private javax.swing.JTextField nom_cam;
    private javax.swing.JTextField nom_chofer;
    private javax.swing.JTextField placas_cam;
    private javax.swing.JButton reg_camion;
    private javax.swing.JButton reg_chofer;
    private javax.swing.JPanel registro_cam;
    private javax.swing.JPanel registro_chofer;
    private javax.swing.JButton return1;
    private javax.swing.JButton return2;
    private javax.swing.JButton return3;
    private javax.swing.JButton return4;
    private javax.swing.JTextField solic;
    private javax.swing.JTextField tel_chofer;
    private javax.swing.JButton verViajeB;
    private javax.swing.JPanel ver_viaje;
    private javax.swing.JComboBox<String> viajesIdBox;
    // End of variables declaration//GEN-END:variables
}
